apiVersion: v1
kind: Service # type of ClusterIP
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # can be different
      targetPort: 3000


